import { Request, Response } from "express";
import { getSupabaseAdmin } from "../config/supabase";

export async function getFamilyDecision(req: Request, res: Response) {
  const { data, error } = await getSupabaseAdmin()
    .from("family_decisions")
    .select("*")
    .eq("user_id", req.user!.id)
    .maybeSingle();
  if (error) throw new Error(error.message);
  res.json({ decision: data ?? null });
}

export async function saveFamilyDecision(req: Request, res: Response) {
  const payload = req.body ?? {};
  const { error } = await getSupabaseAdmin()
    .from("family_decisions")
    .upsert({ user_id: req.user!.id, data: payload, updated_at: new Date().toISOString() });
  if (error) throw new Error(error.message);
  res.json({ decision: payload });
}

export async function getAffordability(req: Request, res: Response) {
  // Honest-by-default: only verified rows are returned. No fabricated figures.
  const { data, error } = await getSupabaseAdmin().from("affordability_entries").select("*").limit(50);
  if (error) throw new Error(error.message);
  res.json({ entries: data ?? [], available: (data ?? []).length > 0 });
}

export async function listScholarships(_req: Request, res: Response) {
  const { data, error } = await getSupabaseAdmin().from("scholarships").select("*").limit(50);
  if (error) throw new Error(error.message);
  res.json({ scholarships: data ?? [], available: (data ?? []).length > 0 });
}

export async function aiExplain(req: Request, res: Response) {
  const apiKey = process.env.OPENAI_API_KEY ?? process.env.DISHAAI_API_KEY;
  const context = req.body?.context;
  if (!context) {
    res.status(400).json({ error: "validation_error", message: "Structured context is required." });
    return;
  }
  if (!apiKey) {
    // Safe deterministic fallback â€” never hallucinate.
    res.json({
      explanation:
        "AI explanation is unavailable because no OPENAI_API_KEY/DISHAAI_API_KEY is configured. Your recommendation above is generated by CareerSathi's deterministic scoring rules and remains valid.",
      aiEnabled: false,
    });
    return;
  }
  try {
    const r = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: process.env.OPENAI_MODEL ?? "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content:
              "You are CareerSathi's explanation assistant for vocational education pathways in India. Explain only the structured context provided. Never change rankings, never invent eligibility, costs, or scholarships, never override constraints, and never claim scientific validity.",
          },
          { role: "user", content: JSON.stringify(context) },
        ],
        temperature: 0.4,
      }),
    });
    const json = (await r.json()) as { choices?: Array<{ message: { content: string } }> };
    res.json({ explanation: json.choices?.[0]?.message?.content ?? "No explanation generated.", aiEnabled: true });
  } catch {
    res.status(502).json({ error: "ai_unavailable", message: "AI service request failed." });
  }
}
